//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruzhokDemkaV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int MaterialTypeID { get; set; }
        public int QuantityInPackage { get; set; }
        public int UnitID { get; set; }
        public int Stock { get; set; }
        public int MinStock { get; set; }
        public decimal Cost { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
