//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruzhokDemkaV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public decimal MinCost { get; set; }
        public string ImagePath { get; set; }
        public int ProductTypeID { get; set; }
        public int WorkersRequired { get; set; }
        public int WorkshopID { get; set; }
    
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
